language: python3.5
dist: trusty
sudo: false

matrix:
  exclude:
    - python: 2.6
  include:
    - python: 3.5

install:
  - "pip install ."
  - "pip install virtualenv"
  - "pip install coveralls"
script:
  - "make test"
after_success: "if [ $TRAVIS_OS_NAME == linux ] ; then coveralls ; fi"
cache: pip
